# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.5
loom_version=1.18-SNAPSHOT

# Mod Properties
version=1.0.0
group=net.tws.finalfrontier

ls_version=1.8.0+beta6-fabric-26.2
dp_version=2.2.1-fabric-26.2
rrv_version=8.10.9
trinkets_version=4.1.1+26.2

# Dependencies
fabric_api_version=0.161.0+26.2
